#!/usr/bin/env sh
exec guile --r7rs -e main -s "$0" "$@"
!#

(import (lsp-server)
        (lsp-server guile)
        (only (lsp-server private) write-log)
        (scheme base)
        (scheme process-context)
        (scheme write)
        (srfi srfi-18)
        (srfi srfi-28))

(define (main args)
  (define command-port-number (string->number (list-ref args 1)))
  (define lsp-port-number (string->number (list-ref args 2)))
  (define lsp-error-port-number (string->number (list-ref args 3)))
  (define log-level (string->symbol (list-ref args 4)))

  (write-log 'debug
             (format
              "Requesting through command port ~a main connection at ~a and error connection at ~a "
              command-port-number
              lsp-port-number
              lsp-error-port-number))
  (parameterize ((lsp-server-log-level log-level))
    (lsp-server-request-connection command-port-number
                                   lsp-port-number
                                   lsp-error-port-number)))
