(define log-level (make-parameter 3))

(define (get-log-level symb)
  (cond ((eqv? symb 'error) 0)
        ((eqv? symb 'warning) 1)
        ((eqv? symb 'info) 2)
        ((eqv? symb 'debug) 3)
        (else (error "invalid log level" symb))))

(define (write-log type msg . args)
  (define level (get-log-level type))
  (define error-port (current-error-port))
  (when (<= level (json-rpc-log-level))
    (display (format "[~a] ~a"
                     (string-upcase (symbol->string type))
                     msg)
              error-port)
    (when (not (null? args))
      (display ": " error-port)
      (map (lambda (s)
             (display (format "~a    " s) error-port))
           args))
    (newline error-port)
    (flush-output-port error-port)))

