#!/usr/bin/env sh
exec guile -e  main -s "$0" "$@"
!#

(import (lsp-server)
        (scheme process-context))

(define (main args)
  (define debug-level
    (if (> (length args) 1)
        (string->symbol (cadr args))
        'error))
  (parameterize ((lsp-server-log-level debug-level))
    (lsp-server-start/stdio)))

(main (command-line))
